const pairs = {
    'AB': 'Antonio Buna-cruz',
    'AC': 'Air-Con',
    'AD': 'Alex Dixon',
    'AE': 'Albert Einstein',
    'AF': 'AFraid',
    'AG': 'AnGel',
    'AH': 'pang AHit',
    'AI': 'AI robot',
    'AJ': 'AJax bar',
    'AK': 'inAKay na ibon',
    'AL': 'aluminum',
    'AM': 'ate AMie',
    'AN': 'ANne/kape',
    'AO': 'AbO/ash',
    'AP': 'APple',
    'AQ': 'AQuarium',
    'AR': 'ARiana',
    'AS': 'ASwang',
    'AT': 'ATlantis',
    'AU': 'gold',
    'AV': 'AloVera',
    'AW': 'ArroW',
    'AX': 'AXe',
    'BA': 'BAal',
    'BC': 'BrocColi',
    'BD': 'BeD',
    'BE': 'BEe',
    'BF': 'ButterFly',
    'BG': 'BaG',
    'BH': 'Baho/base guitar',
    'BI': 'BIo man',
    'BJ': 'banjo',
    'BK': 'book',
    'BL': 'BalL',
    'BM': 'Boom/explosion',
    'BN': 'BeaNs',
    'BO': 'BO sanches',
    'BP': 'BeePer',
    'BQ': 'BarbeQue',
    'BR': 'BiRd',
    'BS': 'BuS',
    'BT': 'BaT',
    'BU': 'BeaUtiful',
    'BV': 'BeaVer',
    'BW': 'BoW',
    'BX': 'BoX',
    'CA': 'CAnada',
    'CB': 'CowBoy',
    'CD': 'CD/disk',
    'CE': 'sea',
    'CF': 'CofFee',
    'CG': 'CowGirl',
    'CH': 'CHurch',
    'CI': 'cyclone',
    'CJ': 'cage',
    'CK': 'CaKe',
    'CL': 'CLock',
    'CM': 'CoMb',
    'CN': 'CaN',
    'CO': 'ChocO',
    'CP': 'CellPhone',
    'CQ': 'cockroach',
    'CR': 'CaR',
    'CS': 'Case',
    'CT': 'CaT',
    'CU': 'CUrrency',
    'CV': 'CaVe',
    'CW': 'CoW',
    'CX': 'cross',
    'DA': 'DarnA',
    'DB': 'DumBell',
    'DC': 'DiCe',
    'DE': 'DEde',
    'DF': 'DragonFly',
    'DG': 'DoG',
    'DH': 'Domestic Helper',
    'DI': 'Dance Instructor',
    'DJ': 'DJ',
    'DK': 'Dike',
    'DL': 'DolL',
    'DM': 'DaM',
    'DN': 'DoNa',
    'DO': 'DOugh',
    'DP': 'Dip/sawsawan',
    'DQ': 'duck',
    'DR': 'Dragon',
    'DS': 'DieSel',
    'DT': 'DaTes',
    'DU': 'DUe date bill',
    'DV': 'DeVil',
    'DW': 'DeW',
    'DX': 'desk',
    'EA': 'EAgle',
    'EB': 'ElBow',
    'EC': 'ECho',
    'ED': 'EDu manzano',
    'EF': 'ElFe',
    'EG': 'EGg',
    'EH': 'Eraser Head',
    'EI': 'EIlin/ellen',
    'EJ': 'Elton John',
    'EK': 'electric',
    'EL': 'Elephant',
    'EM': 'Elena Matias',
    'EN': 'ENergy/portal',
    'EO': 'ErOplano',
    'EP': 'EarPhone',
    'EQ': 'EarthQuake',
    'ER': 'EaR',
    'ES': 'ESoteric symbols',
    'ET': 'Extra Terrestrial/alien',
    'EU': 'EUgene',
    'EV': 'EVe',
    'EW': 'EarWax',
    'EX': 'EX/ekis',
    'FA': 'FireArms',
    'FB': 'FireBall',
    'FC': 'FaCe',
    'FD': 'FooD',
    'FE': 'iron',
    'FG': 'FoG',
    'FH': 'FireHose',
    'FI': 'Fire',
    'FJ': 'forge',
    'FK': 'FaKe/play money',
    'FL': 'Fall',
    'FM': 'Freddi Mercury',
    'FN': 'Fan',
    'FO': 'FOam',
    'FP': 'Fernando Poe',
    'FQ': 'FreQuency/signal',
    'FR': 'priest',
    'FS': 'FoSsil',
    'FT': 'FeeT',
    'FU': 'FUme',
    'FV': 'FlaVio/panday',
    'FW': 'FireWorks',
    'FX': 'FoX',
    'GA': 'GAllon',
    'GB': 'GloBe',
    'GC': 'GloCk-9',
    'GD': 'GoD',
    'GE': 'GE/general electric',
    'GF': 'gift',
    'GH': 'GoHan',
    'GI': 'GIant',
    'GJ': 'ginger',
    'GK': 'GoKu',
    'GL': 'GLue',
    'GM': 'GuM',
    'GN': 'GiN',
    'GO': 'GO sign',
    'GP': 'Gap/bangin',
    'GQ': 'geecko',
    'GR': 'GiRl',
    'GS': 'GaS',
    'GT': 'GaTe',
    'GU': 'GUgo/balat ng puno',
    'GV': 'GuaVa',
    'GW': 'GWardya',
    'GX': 'ate guy',
    'HA': 'HAlls candy',
    'HB': 'HemogloBin',
    'HC': 'HeliCopter',
    'HD': 'Head',
    'HE': 'helium',
    'HF': 'HydroFluoric acid',
    'HG': 'mercury',
    'HI': 'waving hand',
    'HJ': 'headgehog',
    'HK': 'Hello Kitty',
    'HL': 'HelL',
    'HM': 'Hammer',
    'HN': 'HeN',
    'HO': 'HOle',
    'HP': 'Holy Place',
    'HQ': 'hacker',
    'HR': 'HoRse',
    'HS': 'House',
    'HT': 'Hat',
    'HU': 'HU band',
    'HV': 'HoVer board',
    'HW': 'Holy Water',
    'HX': 'hulk',
    'IA': 'upside down robot',
    'IB': 'IBon',
    'IC': 'IC',
    'ID': 'ID',
    'IE': 'Internet Explorer',
    'IF': 'IFfel tower',
    'IG': 'IGlo',
    'IH': 'farming tractor',
    'IJ': 'eject',
    'IK': 'IK-ik/mananangal',
    'IL': 'IsLand',
    'IM': 'IMo app',
    'IN': 'INk',
    'IO': 'IO moon',
    'IP': 'IP man/donie yang',
    'IQ': 'brain',
    'IR': 'InfraRed',
    'IS': 'ISs',
    'IT': 'program code',
    'IU': 'k pop singer',
    'IV': 'IVory',
    'IW': 'eye witness/all seing eye',
    'IX': 'eye with x shaped mark',
    'JA': 'JApan',
    'JB': 'JolliBee',
    'JC': 'Jesus Christ',
    'JD': 'Jedi',
    'JE': 'Joseph Estrada',
    'JF': 'JeF',
    'JG': 'Jaguar',
    'JH': 'yna JoHansen',
    'JI': 'JImmy, santos',
    'JK': 'charlie chaplin',
    'JL': 'John Lennon',
    'JM': 'Jam',
    'JN': 'ate JeN',
    'JO': 'JOe',
    'JP': 'JeeP',
    'JQ': 'jack fruit',
    'JR': 'JaR',
    'JS': 'JeSs',
    'JT': 'JeT',
    'JU': 'JUice',
    'JV': 'JohnVer',
    'JW': 'JaW',
    'JX': 'Jack stone',
    'KA': 'KAmay',
    'KB': 'KoBe',
    'KC': 'KC concepsion',
    'KD': 'KeiDie',
    'KE': 'KEy',
    'KF': 'Kung Fu',
    'KG': 'KanGaroo',
    'KH': 'KaHol',
    'KI': 'KIte',
    'KJ': 'cottage',
    'KL': 'KiLler/jason',
    'KM': 'KiM chui',
    'KN': 'KataNa',
    'KO': 'KOrn',
    'KP': 'KaPa',
    'KQ': 'cocoon',
    'KR': 'Keanu Ribs',
    'KS': 'KiSs',
    'KT': 'KeTtle',
    'KU': 'KUto',
    'KV': 'KiVy app',
    'KW': 'Kwintas',
    'KX': 'kenshin',
    'LA': 'LA-la crackers',
    'LB': 'Lazer Beam',
    'LC': 'LoCk',
    'LD': 'Leonardo Davinci',
    'LE': 'bruce LEe',
    'LF': 'LeaF',
    'LG': 'LG brand',
    'LH': 'LaHar',
    'LI': 'litium battery',
    'LJ': 'lodge',
    'LK': 'Lake',
    'LM': 'LaMb',
    'LN': 'LioN',
    'LO': 'LOlo',
    'LP': 'LooP',
    'LQ': 'LiQour',
    'LR': 'LauRenz',
    'LS': 'LeSlie',
    'LT': 'LighTer',
    'LU': 'LUlu the bear',
    'LV': 'Louis viton',
    'LW': 'Law hammer',
    'LX': 'LuX soap',
    'MA': 'MAria',
    'MB': 'MarlBoro',
    'MC': 'Micheal Casiano',
    'MD': 'MuD',
    'ME': 'Mutya Ella',
    'MF': 'MaFe',
    'MG': 'MuG',
    'MH': 'MaHadi',
    'MI': 'MaI mai',
    'MJ': 'Micheal Jackson',
    'MK': 'Monkey',
    'ML': 'Mona Lisa',
    'MN': 'MoNey',
    'MO': 'Moon',
    'MP': 'MaP',
    'MQ': 'macrina',
    'MR': 'MaRlyn',
    'MS': 'MouSe',
    'MT': 'MaT',
    'MU': 'MUcus',
    'MV': 'MarVel',
    'MW': 'MeadoW',
    'MX': 'marie sabay',
    'NA': 'asin/sodium',
    'NB': 'NoteBook',
    'NC': 'NiCk',
    'ND': 'Nadine',
    'NE': 'NEon light',
    'NF': 'kNiFe',
    'NG': 'NeGro',
    'NH': 'NaiHi',
    'NI': 'bill nye',
    'NJ': 'NinJa',
    'NK': 'NiKe',
    'NL': 'NiLo',
    'NM': 'NiMo',
    'NO': 'NarutO',
    'NP': 'NaPkin',
    'NQ': 'neck',
    'NR': 'NoRalyn',
    'NS': 'NoSe',
    'NT': 'NuT',
    'NU': 'NUke',
    'NV': 'NaVy',
    'NW': 'Nort-West/compas',
    'NX': 'Nunchuck',
    'OA': 'coco martin',
    'OB': 'OBlong',
    'OC': 'Oliver Camus',
    'OD': 'uOD',
    'OE': 'OwEn',
    'OF': 'switched OFf',
    'OG': 'OGer',
    'OH': 'moaning',
    'OI': 'OIl',
    'OJ': 'sabitan ng susi',
    'OK': 'stick man',
    'OL': 'OLympic torch',
    'OM': 'Old Man',
    'ON': 'switched ON',
    'OP': 'OPium',
    'OQ': 'octopus',
    'OR': 'ORe',
    'OS': 'OSo',
    'OT': 'OaT meal',
    'OU': 'alulong',
    'OV': 'OVen',
    'OW': 'OWl',
    'OX': 'orchids',
    'PA': 'Princess Ashley',
    'PB': 'lead',
    'PC': 'computer',
    'PD': 'PaD',
    'PE': 'PE uniform',
    'PF': 'PuFf',
    'PG': 'PaGe',
    'PH': 'PHilippines',
    'PI': 'PIe',
    'PJ': 'PaJama',
    'PK': 'Picolo',
    'PL': 'PoLe',
    'PM': 'Pepper Mint',
    'PN': 'Pan',
    'PO': 'POlice',
    'PQ': 'parachute',
    'PR': 'PRince',
    'PS': 'PenSil',
    'PT': 'PoT',
    'PU': 'PUma',
    'PV': 'PaVement',
    'PW': 'PaW',
    'PX': 'PiXel',
    'QA': 'kuwala',
    'QB': 'cube',
    'QC': 'Quezon Circle',
    'QD': 'sQuiD',
    'QE': 'Queen Elizabeth',
    'QF': 'cough',
    'QG': 'kwago',
    'QH': 'alcohol',
    'QI': 'QuIte',
    'QJ': 'squeezer',
    'QK': 'QuicK',
    'QL': 'QuaiL egg',
    'QM': 'cherubim',
    'QN': 'QueeN',
    'QO': 'QuOte',
    'QP': 'coupon',
    'QR': 'choir',
    'QS': 'cue stick',
    'QT': 'cue tip',
    'QU': 'cute',
    'QV': 'QuiVer',
    'QW': 'Qiwi',
    'QX': 'cutix',
    'RA': 'RA/eiptian god',
    'RB': 'RaBbit',
    'RC': 'RaCe',
    'RD': 'RoaD',
    'RE': 'kuya REne',
    'RF': 'ReFrigerator',
    'RG': 'RuG',
    'RH': 'Red Horse beer',
    'RI': 'RIbbon',
    'RJ': 'radio',
    'RK': 'RocK',
    'RL': 'RaiL',
    'RM': 'RaM',
    'RN': 'RaiN',
    'RO': 'ROger',
    'RP': 'RoPe',
    'RQ': 'rocket',
    'RS': 'RoSe',
    'RT': 'RaT',
    'RU': 'RUth',
    'RV': 'RoVer',
    'RW': 'Row',
    'RX': 'doctor',
    'SA': 'Saudi Arabia',
    'SB': 'Snow Ball',
    'SC': 'Samuel Camus',
    'SD': 'SpiDer',
    'SE': 'Seven Elleven',
    'SF': 'SoFa',
    'SG': 'SunGlass',
    'SH': 'Scissor Hand',
    'SI': 'silicon',
    'SJ': 'serge',
    'SK': 'SKy',
    'SL': 'SeLl',
    'SM': 'Super Mario',
    'SN': 'SuN',
    'SO': 'SOco',
    'SP': 'SoaP',
    'SQ': 'SQuare',
    'SR': 'SwoRd',
    'ST': 'foot STep',
    'SU': 'SUe ramirez',
    'SV': 'SalVage',
    'SW': 'SaW',
    'SX': 'sacks',
    'TA': 'TAal',
    'TB': 'TaB',
    'TC': 'tTC',
    'TD': 'TeDdy bear',
    'TE': 'TEa',
    'TF': 'ToFu',
    'TG': 'TiGer',
    'TH': 'Town Hall',
    'TI': 'Tie/Sheo lace',
    'TJ': 'Taj Mahal',
    'TK': 'TicKet',
    'TL': 'TaiL',
    'TM': 'ToM',
    'TN': 'TiNa',
    'TO': 'TOto band',
    'TP': 'TaPe',
    'TQ': 'taco',
    'TR': 'TRee',
    'TS': 'TranSistor',
    'TU': 'TUyo',
    'TV': 'TV',
    'TW': 'ToWer',
    'TX': 'tranks',
    'UA': 'uwak',
    'UB': 'UBe',
    'UC': 'user/addict',
    'UD': 'UnDerground',
    'UE': 'kuya UwE',
    'UF': 'UFo',
    'UG': 'UGoy/duyan',
    'UH': 'UHog',
    'UI': 'User Interface',
    'UJ': 'huge',
    'UK': 'UKay ukay',
    'UL': 'ULing',
    'UM': 'Ultra Man',
    'UN': 'United Nation',
    'UO': 'euro',
    'UP': 'UP arrow',
    'UQ': 'ukelele',
    'UR': 'URinal',
    'US': 'USa',
    'UT': 'UTot',
    'UV': 'UtraViolet',
    'UW': 'UnderWater',
    'UX': 'usher',
    'VA': 'VAlve',
    'VB': 'ValleyBall',
    'VC': 'ViC sotto',
    'VD': 'ViDeo',
    'VE': 'VEin',
    'VF': 'vandolf',
    'VG': 'vegetable',
    'VH': 'VHs tape',
    'VI': 'Vialyn',
    'VJ': 'vintage',
    'VK': 'vikings',
    'VL': 'VioLin',
    'VM': 'VaMpire',
    'VN': 'Vong Navarro',
    'VO': 'VOlt',
    'VP': 'VaPor',
    'VQ': 'vacuum',
    'VR': 'Virtual Reality',
    'VS': 'VaSe',
    'VT': 'VoTe',
    'VU': 'view',
    'VW': 'VolksWagen',
    'VX': 'vicks',
    'WA': 'WAnd',
    'WB': 'WeB',
    'WC': 'WitChraft',
    'WD': 'WooD',
    'WE': 'WEed',
    'WF': 'WaFfle/waffer',
    'WG': 'WiG',
    'WH': 'WHale',
    'WI': 'pocket WIfi',
    'WJ': 'WaJid/one rial',
    'WK': 'WaKwak',
    'WL': 'WaLl',
    'WM': 'WorM',
    'WN': 'Wonder womaN',
    'WO': 'WOrld',
    'WP': 'WiPer',
    'WQ': 'wacky',
    'WR': 'WaR',
    'WS': 'WaSte',
    'WT': 'WaTer',
    'WU': 'WoUnd',
    'WV': 'WaVe',
    'WX': 'WaX',
    'XA': 'sha sha',
    'XB': 'shabu',
    'XC': 'screw',
    'XD': 'shade',
    'XE': 'che che',
    'XF': 'sheff',
    'XG': 'shaggy',
    'XH': 'yahoo',
    'XI': 'china',
    'XJ': 'soldier',
    'XK': 'skate',
    'XL': 'shell',
    'XM': 'X Men',
    'XN': 'shine',
    'XO': 'shishio',
    'XP': 'shop',
    'XQ': 'chacky',
    'XR': 'X-Ray',
    'XS': 'chess',
    'XT': 'XTention',
    'XU': 'sheos',
    'XV': 'shovel',
    'XW': 'shower',
};

// export default pairs;
const letterList = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
    'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X'];

const letterStock = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
    'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X'];


const data = {letterList, pairs, letterStock};
export default data;